// Generated by gencpp from file phasespace/Markers.msg
// DO NOT EDIT!


#ifndef PHASESPACE_MESSAGE_MARKERS_H
#define PHASESPACE_MESSAGE_MARKERS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <phasespace/Marker.h>

namespace phasespace
{
template <class ContainerAllocator>
struct Markers_
{
  typedef Markers_<ContainerAllocator> Type;

  Markers_()
    : markers()  {
    }
  Markers_(const ContainerAllocator& _alloc)
    : markers(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::phasespace::Marker_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::phasespace::Marker_<ContainerAllocator> >::other >  _markers_type;
  _markers_type markers;





  typedef boost::shared_ptr< ::phasespace::Markers_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::phasespace::Markers_<ContainerAllocator> const> ConstPtr;

}; // struct Markers_

typedef ::phasespace::Markers_<std::allocator<void> > Markers;

typedef boost::shared_ptr< ::phasespace::Markers > MarkersPtr;
typedef boost::shared_ptr< ::phasespace::Markers const> MarkersConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::phasespace::Markers_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::phasespace::Markers_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::phasespace::Markers_<ContainerAllocator1> & lhs, const ::phasespace::Markers_<ContainerAllocator2> & rhs)
{
  return lhs.markers == rhs.markers;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::phasespace::Markers_<ContainerAllocator1> & lhs, const ::phasespace::Markers_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace phasespace

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::phasespace::Markers_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phasespace::Markers_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phasespace::Markers_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phasespace::Markers_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phasespace::Markers_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phasespace::Markers_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::phasespace::Markers_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd435738f02ace3b863bc0a3b36d34db";
  }

  static const char* value(const ::phasespace::Markers_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd435738f02ace3bULL;
  static const uint64_t static_value2 = 0x863bc0a3b36d34dbULL;
};

template<class ContainerAllocator>
struct DataType< ::phasespace::Markers_<ContainerAllocator> >
{
  static const char* value()
  {
    return "phasespace/Markers";
  }

  static const char* value(const ::phasespace::Markers_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::phasespace::Markers_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Marker[] markers\n"
"================================================================================\n"
"MSG: phasespace/Marker\n"
"uint32 id\n"
"uint32 flags\n"
"uint64 time\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 cond\n"
;
  }

  static const char* value(const ::phasespace::Markers_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::phasespace::Markers_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.markers);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Markers_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::phasespace::Markers_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::phasespace::Markers_<ContainerAllocator>& v)
  {
    s << indent << "markers[]" << std::endl;
    for (size_t i = 0; i < v.markers.size(); ++i)
    {
      s << indent << "  markers[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::phasespace::Marker_<ContainerAllocator> >::stream(s, indent + "    ", v.markers[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PHASESPACE_MESSAGE_MARKERS_H
