// Generated by gencpp from file phasespace/Rigids.msg
// DO NOT EDIT!


#ifndef PHASESPACE_MESSAGE_RIGIDS_H
#define PHASESPACE_MESSAGE_RIGIDS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <phasespace/Rigid.h>

namespace phasespace
{
template <class ContainerAllocator>
struct Rigids_
{
  typedef Rigids_<ContainerAllocator> Type;

  Rigids_()
    : rigids()  {
    }
  Rigids_(const ContainerAllocator& _alloc)
    : rigids(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::phasespace::Rigid_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::phasespace::Rigid_<ContainerAllocator> >::other >  _rigids_type;
  _rigids_type rigids;





  typedef boost::shared_ptr< ::phasespace::Rigids_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::phasespace::Rigids_<ContainerAllocator> const> ConstPtr;

}; // struct Rigids_

typedef ::phasespace::Rigids_<std::allocator<void> > Rigids;

typedef boost::shared_ptr< ::phasespace::Rigids > RigidsPtr;
typedef boost::shared_ptr< ::phasespace::Rigids const> RigidsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::phasespace::Rigids_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::phasespace::Rigids_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::phasespace::Rigids_<ContainerAllocator1> & lhs, const ::phasespace::Rigids_<ContainerAllocator2> & rhs)
{
  return lhs.rigids == rhs.rigids;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::phasespace::Rigids_<ContainerAllocator1> & lhs, const ::phasespace::Rigids_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace phasespace

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::phasespace::Rigids_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phasespace::Rigids_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phasespace::Rigids_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phasespace::Rigids_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phasespace::Rigids_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phasespace::Rigids_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::phasespace::Rigids_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a8f3dae161da20e992e073ef65cea8a4";
  }

  static const char* value(const ::phasespace::Rigids_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa8f3dae161da20e9ULL;
  static const uint64_t static_value2 = 0x92e073ef65cea8a4ULL;
};

template<class ContainerAllocator>
struct DataType< ::phasespace::Rigids_<ContainerAllocator> >
{
  static const char* value()
  {
    return "phasespace/Rigids";
  }

  static const char* value(const ::phasespace::Rigids_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::phasespace::Rigids_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Rigid[] rigids\n"
"================================================================================\n"
"MSG: phasespace/Rigid\n"
"uint32 id\n"
"uint32 flags\n"
"uint64 time\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 qw\n"
"float32 qx\n"
"float32 qy\n"
"float32 qz\n"
"float32 cond\n"
;
  }

  static const char* value(const ::phasespace::Rigids_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::phasespace::Rigids_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rigids);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Rigids_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::phasespace::Rigids_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::phasespace::Rigids_<ContainerAllocator>& v)
  {
    s << indent << "rigids[]" << std::endl;
    for (size_t i = 0; i < v.rigids.size(); ++i)
    {
      s << indent << "  rigids[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::phasespace::Rigid_<ContainerAllocator> >::stream(s, indent + "    ", v.rigids[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PHASESPACE_MESSAGE_RIGIDS_H
